//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PharmacyApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Batches
    {
        public int BatchID { get; set; }
        public int DrugID { get; set; }
        public string BatchNumber { get; set; }
        public System.DateTime ExpiryDate { get; set; }
        public int Quantity { get; set; }
    
        public virtual Drugs Drugs { get; set; }
    }
}
