//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PharmacyApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale_Items
    {
        public int SaleItemID { get; set; }
        public int SaleID { get; set; }
        public int DrugID { get; set; }
        public int Quantity { get; set; }
        public decimal Price { get; set; }
    
        public virtual Drugs Drugs { get; set; }
        public virtual Sales Sales { get; set; }
    }
}
